worker_processes 1;
pid /run/sv08-mainsail/nginx.pid;
error_log /var/log/printer/mainsail-error.log;
events { worker_connections 256; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/printer/mainsail-access.log;
    client_body_temp_path /run/sv08-mainsail/body;
    proxy_temp_path /run/sv08-mainsail/proxy;
    fastcgi_temp_path /run/sv08-mainsail/fastcgi;
    uwsgi_temp_path /run/sv08-mainsail/uwsgi;
    scgi_temp_path /run/sv08-mainsail/scgi;
    include /run/sv08/printer_data/config/nginx-mainsail.conf;
}
