"""Offline Chromium journeys; Cockpit and software backend are disposable mocks."""
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

REPO = Path(__file__).resolve().parents[1]
NODE = Path('/home/drew/sv08-mainline/build/mainsail-package-v6/node-v22.23.2-linux-x64/bin/node')
CHROME = Path('/home/drew/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome')
SCRATCH = Path('/home/drew/.sv08-software-ui-20261009')

JOURNEYS = r'''
import fs from 'node:fs';import http from 'node:http';import https from 'node:https';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import assert from 'node:assert/strict';
const [repo,chrome,work]=process.argv.slice(2);const profile=path.join(work,'profile');const downloads=path.join(work,'downloads');fs.mkdirSync(downloads);
const mock=`window.sv08Session={elevated:true,ready:Promise.resolve()};window.requests=[];window.hold=false;window.held=[];window.failPlan='';window.planAllowed=true;window.failApply=false;window.job=null;
window.snapshot=()=>({catalog:[{package:'nano',title:'Text editor',description:'Edit files',packages:['nano'],dependencies:['libncurses'],installed:false},{package:'vnstat',title:'Traffic monitor',packages:['vnstat'],installed:true,service:'vnstat.service',service_state:{UnitFileState:'enabled',ActiveState:'running'}}],customized:true,capabilities:{install:{available:true},reconcile:{available:false}},reconciliation:{exports:['job-one'],reason:'Package changes remain installed.'},jobs:job?[job]:[]});
window.cockpit={spawn(args,options){if(args.join(' ')!='/usr/bin/python3 /usr/lib/sv08/sv08_software.py'||options.superuser!=='require')throw Error('wrong transport');return {input(text){const r=JSON.parse(text);requests.push(r);if(r.method==='status'&&hold)return new Promise(resolve=>held.push(resolve));if(r.method==='inspect') return JSON.stringify({ok:true,result:{warning:'Review uncertainty',dpkg_audit:'',policy_recovery_required:false,evidence:{inventory:[['nano','1.0','arm64']]}}});if(r.method==='plan'){if(failPlan)return Promise.resolve(JSON.stringify({ok:false,error:failPlan}));return Promise.resolve(JSON.stringify({ok:true,result:{token:'plan-one',digest:'digest-one',available:planAllowed,reason:planAllowed?'':'Writable mode is required',action:r.action,arguments:r.arguments,preview:{install:[{package:r.arguments.package,version:'1.0'}],remove:[],service_effect:'Service stops and is disabled before removal',download_bytes:1048576,installed_delta_bytes:2097152,required_bytes:3145728,root_free_bytes:4194304,data_reserve_bytes:1048576,data_free_bytes:8388608}}}))}if(r.method==='apply'){job={id:'job-one',state:'running',phase:'install',progress:40};if(failApply){failApply=false;return Promise.reject(Error('Disconnected'))}return Promise.resolve(JSON.stringify({ok:true,result:job}))}return Promise.resolve(JSON.stringify({ok:true,result:r.method==='reconciliation-export'?{packages:['nano'],reason:'Customized'}:snapshot()}));}}}};`;
const server=http.createServer((req,res)=>{let name=req.url.split('?')[0];if(name==='/') {res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(repo+'/ui/host/index.html','utf8').replace(/<script[^>]*>.*?<\/script>/g,'') .replace('</head>','<script>'+mock+'</script><script defer src="/navigation.js"></script><script defer src="/software.js"></script></head>'));}else if(['/navigation.js','/software.js','/style.css'].includes(name)){res.end(fs.readFileSync(repo+'/ui/host'+name));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'0.0.0.0',r));const port=server.address().port;
spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',work+'/key.pem','-out',work+'/cert.pem','-subj','/CN=localhost','-days','1'],{stdio:'ignore'});const tls=https.createServer({key:fs.readFileSync(work+'/key.pem'),cert:fs.readFileSync(work+'/cert.pem')},server.listeners('request')[0]);await new Promise(r=>tls.listen(0,'127.0.0.1',r));
let child,socket;try{
child=spawn(chrome,['--headless','--ignore-certificate-errors','--no-sandbox','--disable-gpu','--disable-background-networking','--no-proxy-server','--host-resolver-rules=MAP printer.test 127.0.0.1','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore',detached:true});let debug;for(let i=0;i<100;i++){try{debug=fs.readFileSync(profile+'/DevToolsActivePort','utf8').split('\n')[0];break;}catch{await delay(50)}}assert(debug);
const tabs=await(await fetch('http://127.0.0.1:'+debug+'/json/list')).json();socket=new WebSocket(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j});let id=0;const pending=new Map();const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;const timer=setTimeout(()=>reject(Error('CDP timeout')),10000);pending.set(n,{resolve,reject,timer});socket.send(JSON.stringify({id:n,method,params}));});socket.onmessage=({data})=>{const e=JSON.parse(data),p=pending.get(e.id);if(p){pending.delete(e.id);clearTimeout(p.timer);e.error?p.reject(Error(JSON.stringify(e.error))):p.resolve(e.result)}};
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};const until=async expression=>{for(let i=0;i<100;i++){if(await ev(expression))return;await delay(30)}throw Error('condition: '+expression)};const click=id=>ev(`document.getElementById('${id}').click()`);const fill=(id,value)=>ev(`document.getElementById('${id}').value=${JSON.stringify(value)};document.getElementById('${id}').dispatchEvent(new Event('input'))`);const close=value=>ev(`document.getElementById('software-review').close('${value}')`);
await send('Page.navigate',{url:'http://localhost:'+port+'/#overview'});await until('window.sv08Navigation');await ev(`hold=true;sv08Navigation.go('software')`);await until('held.length===1');assert(await ev(`document.getElementById('software-status').textContent.includes('Loading') && document.getElementById('software-install').disabled`));await ev(`hold=false;held.shift()(JSON.stringify({ok:true,result:snapshot()}))`);await until(`!document.getElementById('software-install').disabled`);assert(await ev(`document.getElementById('notice').hidden && document.getElementById('jobs-summary').closest('article').hidden`));
assert(await ev(`document.getElementById('software-dependencies').textContent.includes('libncurses')`));await click('software-install');await until(`document.getElementById('software-review').open`);assert(await ev(`document.getElementById('software-review-detail').textContent.includes('Download: 1.0 MiB') && document.getElementById('software-review-detail').textContent.includes('Data space available: 8.0 MiB')`));await close('cancel');await delay(40);assert.equal(await ev(`requests.filter(r=>r.method==='apply').length`),0);
await click('software-install');await until(`document.getElementById('software-review').open`);await close('confirm');await until(`document.getElementById('software-job-detail').textContent.includes('40%')`);assert.deepEqual(await ev(`requests.find(r=>r.method==='apply')`),{method:'apply',token:'plan-one',digest:'digest-one'});
await ev(`sv08Navigation.go('overview');job.state='failed';job.error='Package conflict';sv08Navigation.go('software')`);await until(`document.getElementById('software-job-detail').textContent.includes('Package conflict')`);
for(const reason of ['Writable mode is required','Not enough disk space','Package conflict']){await ev('failPlan='+JSON.stringify(reason));await click('software-install');await until(`document.getElementById('software-status').textContent.includes(${JSON.stringify(reason)})`);assert(!(await ev(`document.getElementById('software-review').open`)))}await ev(`failPlan='';planAllowed=false`);await click('software-install');await until(`document.getElementById('software-review').open`);assert(await ev(`document.getElementById('software-confirm').disabled && document.getElementById('software-review-detail').textContent.includes('Writable mode')`));const deniedBefore=await ev(`requests.filter(r=>r.method==='apply').length`);await close('confirm');await delay(40);assert.equal(await ev(`requests.filter(r=>r.method==='apply').length`),deniedBefore);await ev(`planAllowed=true;failApply=true`);await click('software-install');await until(`document.getElementById('software-review').open`);await close('confirm');await until(`document.getElementById('software-status').textContent.includes('Disconnected')`);await until(`document.getElementById('software-job-detail').textContent.includes('job-one')`);
await ev(`document.getElementById('software-choice').value='vnstat';document.getElementById('software-choice').dispatchEvent(new Event('change'));document.getElementById('software-service-enabled').checked=false`);await click('software-service');await until(`document.getElementById('software-review').open`);assert.deepEqual(await ev(`requests.filter(r=>r.method==='plan').at(-1)`),{method:'plan',action:'service',arguments:{package:'vnstat',enabled:false}});await close('cancel');await click('software-remove');await until(`document.getElementById('software-review').open`);assert.equal(await ev(`requests.filter(r=>r.method==='plan').at(-1).action`),'remove');assert(await ev(`document.getElementById('software-review-detail').textContent.includes('disabled before removal')`));await close('cancel');assert(await ev(`document.getElementById('software-reconciliation').textContent.includes('remain installed') && document.getElementById('software-reconcile').disabled`));
await click('software-export');await until(`document.getElementById('software-status').textContent.includes('downloaded')`);
await ev(`job={id:'uncertain-job',status:'unknown',message:'Interrupted'};sv08Navigation.go('overview');sv08Navigation.go('software')`);await until(`!document.getElementById('software-inspect').hidden`);await click('software-inspect');await until(`document.getElementById('software-review').open`);assert(await ev(`document.getElementById('software-review-detail').textContent.includes('will not repeat')`));assert.deepEqual(await ev(`requests.filter(r=>r.method==='plan').at(-1)`),{method:'plan',action:'acknowledge',arguments:{id:'uncertain-job'}});await close('cancel');
await ev(`sv08Session.elevated=false;window.dispatchEvent(new Event('sv08-authority-changed'))`);assert(await ev(`document.getElementById('software-status').textContent.includes('Administrator access') && document.getElementById('software-refresh').disabled`));await ev(`hold=true;sv08Session.elevated=true;window.dispatchEvent(new Event('sv08-authority-changed'))`);await until('held.length===1');await ev(`sv08Navigation.go('overview');held.shift()(JSON.stringify({ok:true,result:snapshot()}))`);await delay(40);assert.equal(await ev(`document.getElementById('software-choice').options.length`),0);await ev(`hold=false;sv08Navigation.go('software')`);await until(`!document.getElementById('software-install').disabled`);await click('software-install');await until(`document.getElementById('software-review').open`);const before=await ev('requests.length');await ev(`sv08Session.elevated=false;window.dispatchEvent(new Event('sv08-authority-changed'))`);await close('confirm');await delay(40);assert.equal(await ev('requests.length'),before);
for(const width of [390,1024]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});assert(await ev('document.documentElement.scrollWidth<=innerWidth'))}
console.log('PASS: catalog/loading, administrator access, dependency/space review, cancellation/apply, durable resume, conflicts/disk/immutable failures, lost response, service/removal, export, stale navigation/authority, responsive views');
}finally{socket?.close();server.close();tls.close();if(child){try{process.kill(-child.pid,'SIGTERM')}catch{}await delay(100);try{process.kill(-child.pid,'SIGKILL')}catch{}}}
'''


class SoftwareBrowserTests(unittest.TestCase):
    def test_mocked_browser_journeys(self):
        self.assertTrue(NODE.exists(), 'Assigned Node tool is required')
        self.assertTrue(CHROME.exists(), 'Assigned Chromium tool is required')
        SCRATCH.mkdir(mode=0o700, parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=SCRATCH) as temporary:
            script = Path(temporary)/'journeys.mjs'
            script.write_text(JOURNEYS)
            result = subprocess.run([str(NODE),str(script),str(REPO),str(CHROME),temporary],capture_output=True,text=True,timeout=120)
            self.assertEqual(result.returncode,0,result.stdout+result.stderr)
            print(result.stdout.strip())


if __name__ == '__main__':
    unittest.main()
