"""Offline Chromium journeys; Cockpit and access backend are disposable mocks."""
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

REPO = Path(__file__).resolve().parents[1]
NODE = Path('/home/drew/sv08-mainline/build/mainsail-package-v6/node-v22.23.2-linux-x64/bin/node')
CHROME = Path('/home/drew/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome')
SCRATCH = Path('/home/drew/.sv08-network-ui-20261009')

JOURNEYS = r'''
import fs from 'node:fs';import http from 'node:http';import https from 'node:https';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import assert from 'node:assert/strict';
const [repo,chrome,work]=process.argv.slice(2);const profile=path.join(work,'profile');const downloads=path.join(work,'downloads');fs.mkdirSync(downloads);
const mock=`window.sv08Session={elevated:true,ready:Promise.resolve()};window.requests=[];window.hold=false;window.held=[];window.failApply=false;window.failStatus=false;window.pendingChange=null;
window.snapshot=()=>({devices:[{device:'wlan0',type:'wifi',state:'connected',connection:'Home',uuid:'saved',addresses:['192.168.1.20/24'],gateway:'192.168.1.1',dns:['1.1.1.1']},{device:'eth0',type:'ethernet',state:'disconnected',addresses:[],dns:[]}],connections:[{uuid:'saved',name:'Home',type:'wifi',device:'wlan0',ssid:'Home',security:'wpa-psk',ipv4:{method:'auto',addresses:[],gateway:'',dns:[]}}],hostname:'sv08',fqdn:'sv08.local',pending:pendingChange});
window.cockpit={spawn(args,options){if(args.join(' ')!='/usr/bin/python3 /usr/lib/sv08/sv08_network.py'||options.superuser!=='require')throw Error('wrong transport');return {input(text){const r=JSON.parse(text);requests.push(r);if(r.method==='status'&&failStatus){failStatus=false;return Promise.reject(Error('Status disconnected'))}if(r.method==='status'&&hold)return new Promise(resolve=>held.push(resolve));if(r.method==='apply'){pendingChange={token:'token-one',expires:Date.now()/1000+120};if(failApply){failApply=false;return Promise.reject(Error('Disconnected'))}return Promise.resolve(JSON.stringify({ok:true,result:{...pendingChange,confirm_required:true}}))}if(['confirm','rollback'].includes(r.method))pendingChange=null;return Promise.resolve(JSON.stringify({ok:true,result:r.method==='wifi.scan'?{networks:[{ssid:'New wifi',signal:90,security:'WPA2',in_use:false}]}:snapshot()}));}}}};`;
const server=http.createServer((req,res)=>{let name=req.url.split('?')[0];if(name==='/') {res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(repo+'/ui/host/index.html','utf8').replace(/<script[^>]*>.*?<\/script>/g,'') .replace('</head>','<script>'+mock+'</script><script defer src="/navigation.js"></script><script defer src="/network.js"></script></head>'));}else if(['/navigation.js','/network.js','/style.css'].includes(name)){res.end(fs.readFileSync(repo+'/ui/host'+name));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'0.0.0.0',r));const port=server.address().port;
spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',work+'/key.pem','-out',work+'/cert.pem','-subj','/CN=localhost','-days','1'],{stdio:'ignore'});const tls=https.createServer({key:fs.readFileSync(work+'/key.pem'),cert:fs.readFileSync(work+'/cert.pem')},server.listeners('request')[0]);await new Promise(r=>tls.listen(0,'127.0.0.1',r));
let child,socket;try{
child=spawn(chrome,['--headless','--ignore-certificate-errors','--no-sandbox','--disable-gpu','--disable-background-networking','--no-proxy-server','--host-resolver-rules=MAP printer.test 127.0.0.1','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore',detached:true});let debug;for(let i=0;i<100;i++){try{debug=fs.readFileSync(profile+'/DevToolsActivePort','utf8').split('\n')[0];break;}catch{await delay(50)}}assert(debug);
const tabs=await(await fetch('http://127.0.0.1:'+debug+'/json/list')).json();socket=new WebSocket(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j});let id=0;const pending=new Map();const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;const timer=setTimeout(()=>reject(Error('CDP timeout')),10000);pending.set(n,{resolve,reject,timer});socket.send(JSON.stringify({id:n,method,params}));});socket.onmessage=({data})=>{const e=JSON.parse(data),p=pending.get(e.id);if(p){pending.delete(e.id);clearTimeout(p.timer);e.error?p.reject(Error(JSON.stringify(e.error))):p.resolve(e.result)}};
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};const until=async expression=>{for(let i=0;i<100;i++){if(await ev(expression))return;await delay(30)}throw Error('condition: '+expression)};const click=id=>ev(`document.getElementById('${id}').click()`);const fill=(id,value)=>ev(`document.getElementById('${id}').value=${JSON.stringify(value)};document.getElementById('${id}').dispatchEvent(new Event('input'))`);const close=value=>ev(`document.getElementById('network-review').close('${value}')`);
await send('Page.navigate',{url:'http://localhost:'+port+'/#overview'});await until('window.sv08Navigation');await ev(`hold=true;document.querySelector('[data-page="network"]').click()`);await until('held.length===1');assert(await ev(`document.getElementById('network-status').textContent.includes('Loading network') && document.getElementById('network-apply').disabled`));await ev(`hold=false;held.shift()(JSON.stringify({ok:true,result:snapshot()}))`);await until(`!document.getElementById('network-apply').disabled`);
assert(await ev(`document.getElementById('notice').hidden && document.getElementById('jobs-summary').closest('article').hidden`));
await click('network-scan');await until(`document.getElementById('network-networks').options.length===2`);await ev(`document.getElementById('network-networks').value='0';document.getElementById('network-networks').dispatchEvent(new Event('change'))`);assert.equal(await ev(`document.getElementById('network-ssid').value`),'New wifi');assert.equal(await ev(`document.getElementById('network-security').value`),'wpa-psk');assert.equal(await ev(`document.getElementById('network-connection').value`),'');
// HTTP password submissions are blocked, including programmatic field insertion.
await fill('network-password','secret pass');await click('network-apply');assert(await ev(`document.getElementById('network-status').textContent.includes('Use HTTPS')`));assert.equal(await ev(`document.getElementById('network-password').value`),'');
await click('network-apply');assert(!(await ev(`document.getElementById('network-review-detail').textContent.includes('password')`)));await close('cancel');await delay(40);assert.equal(await ev(`requests.filter(r=>r.method==='apply').length`),0);
await click('network-apply');await close('confirm');await until(`!document.getElementById('network-confirm').disabled`);assert(await ev(`!document.getElementById('network-pending').hidden && document.getElementById('network-countdown').textContent.includes('seconds')`));await click('network-confirm');await until(`document.getElementById('network-pending').hidden`);assert.deepEqual(await ev(`requests.find(r=>r.method==='confirm')`),{method:'confirm',token:'token-one'});
await ev(`document.getElementById('network-connection').value='saved';document.getElementById('network-connection').dispatchEvent(new Event('change'))`);await fill('network-method','manual');await fill('network-addresses','192.168.1.50/24');await fill('network-gateway','192.168.1.1');await fill('network-dns','1.1.1.1,8.8.8.8');await click('network-apply');await close('confirm');await until(`!document.getElementById('network-rollback').disabled`);const reused=await ev(`requests.filter(r=>r.method==='apply').at(-1)`);assert.equal(reused.connection_uuid,'saved');assert.equal(reused.password,'');assert.deepEqual(reused.ipv4,{method:'manual',addresses:['192.168.1.50/24'],gateway:'192.168.1.1',dns:['1.1.1.1','8.8.8.8']});await click('network-rollback');await until(`document.getElementById('network-pending').hidden`);
await ev(`document.getElementById('network-device').value='eth0';document.getElementById('network-device').dispatchEvent(new Event('change'))`);assert(await ev(`document.getElementById('network-wifi').hidden`));await click('network-apply');await close('confirm');await until(`!document.getElementById('network-confirm').disabled`);assert.equal(await ev(`requests.filter(r=>r.method==='apply').at(-1).kind`),'ethernet');await click('network-confirm');await until(`document.getElementById('network-pending').hidden`);
await fill('network-hostname','newname');await fill('network-fqdn','newname.local');await click('network-name');await close('confirm');await until(`!document.getElementById('network-confirm').disabled`);assert.deepEqual(await ev(`requests.filter(r=>r.method==='apply').at(-1)`),{method:'apply',kind:'name',hostname:'newname',fqdn:'newname.local'});await click('network-confirm');await until(`document.getElementById('network-pending').hidden`);
await ev('failApply=true');await click('network-name');await close('confirm');await until(`document.getElementById('network-status').textContent.includes('Disconnected') && !document.getElementById('network-confirm').disabled`);await click('network-rollback');await until(`document.getElementById('network-pending').hidden`);
await click('network-restart');await close('cancel');assert.equal(await ev(`requests.filter(r=>r.method==='restart').length`),0);await click('network-restart');await close('confirm');await until(`document.getElementById('network-status').textContent.includes('Restart requested')`);assert.deepEqual(await ev(`requests.find(r=>r.method==='restart')`),{method:'restart',confirm:true});
await fill('network-password','temporary');await ev(`sv08Session.elevated=false;window.dispatchEvent(new Event('sv08-authority-changed'))`);assert(await ev(`document.getElementById('network-status').textContent.includes('Administrator access is required') && document.getElementById('network-refresh').disabled && document.getElementById('network-password').value===''`));
await ev(`hold=true;sv08Session.elevated=true;window.dispatchEvent(new Event('sv08-authority-changed'))`);await until('held.length===1');await fill('network-password','temporary');await ev(`sv08Navigation.go('overview');held.shift()(JSON.stringify({ok:true,result:snapshot()}))`);await delay(40);assert.equal(await ev(`document.getElementById('network-devices').textContent`),'');assert.equal(await ev(`document.getElementById('network-password').value`),'');
await ev(`hold=false;sv08Navigation.go('network')`);await until(`!document.getElementById('network-name').disabled`);await click('network-name');const before=await ev('requests.length');await ev(`sv08Session.elevated=false;window.dispatchEvent(new Event('sv08-authority-changed'))`);await close('confirm');await delay(40);assert.equal(await ev('requests.length'),before);
for(const width of [390,1024]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});assert(await ev('document.documentElement.scrollWidth<=innerWidth'))}
await send('Page.navigate',{url:'https://localhost:'+tls.address().port+'/#network'});await until(`document.getElementById('network-ssid')?.value==='Home'`);await fill('network-password','private secret');await click('network-apply');assert(!(await ev(`document.getElementById('network-review-detail').textContent.includes('private secret')`)));assert.equal(await ev(`document.getElementById('network-password').value`),'');await close('confirm');await until(`!document.getElementById('network-confirm').disabled`);assert.equal(await ev(`requests.find(r=>r.method==='apply').password`),'private secret');assert(await ev(`Array.from(document.querySelectorAll('#network-links a')).every(a=>new URL(a.href).port===location.port && new URL(a.href).pathname===location.pathname)`));await ev('failStatus=true');await click('network-refresh');await until(`document.getElementById('network-status').textContent.includes('Status disconnected')`);assert(await ev(`!document.getElementById('network-pending').hidden && !document.getElementById('network-confirm').disabled`));await click('network-confirm');await until(`document.getElementById('network-pending').hidden`);
console.log('PASS: HTTPS password, status/loading, limited authority, WiFi scan, password transport/redaction, cancellation, connection/IPv4 reuse, apply/confirm/rollback/lost response, name/restart, authority/navigation stale replies, responsive views');
}finally{socket?.close();server.close();tls.close();if(child){try{process.kill(-child.pid,'SIGTERM')}catch{}await delay(100);try{process.kill(-child.pid,'SIGKILL')}catch{}}}
'''


class NetworkBrowserTests(unittest.TestCase):
    def test_mocked_browser_journeys(self):
        self.assertTrue(NODE.exists(), 'Assigned Node tool is required')
        self.assertTrue(CHROME.exists(), 'Assigned Chromium tool is required')
        SCRATCH.mkdir(mode=0o700, parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=SCRATCH) as temporary:
            script = Path(temporary)/'journeys.mjs'
            script.write_text(JOURNEYS)
            result = subprocess.run([str(NODE),str(script),str(REPO),str(CHROME),temporary],capture_output=True,text=True,timeout=120)
            self.assertEqual(result.returncode,0,result.stdout+result.stderr)
            print(result.stdout.strip())


if __name__ == '__main__':
    unittest.main()
